### PR TITLE
Be more clear about adding validation constraints in the doc

### LINKED ISSUE #767: Incomplete instructions for setting validation constraints?
Hello,

When looking at the Validating tokens part of the doc, one cannot find the `setValidationConstraints()` function call. The code shows `$constraints = $config->validationConstraints();` but this is empty if no constraints have been set beforehand with this function.

One has to look into the source code or the customization part of the doc to find that this exists.

Did I miss something or can I send a patch for the doc?

BTW, thanks for this lib, it is really well made :+1: !

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Fix #767

For me, this is what I think was missing and made me wonder "ok but how do I add a constraint??".

So I added a comment in the code to point to the configuration doc and more importantly an example code after listing the available validationconstraints, at it makes sense to show how to actually use them after listing them.

Cheers,
~Nico

### CODE REVIEW

**Comment by lcobucci** [comment]
Apologies @NicolasCARPi, for some weird reason I missed the notifications on this PR.
Thanks for your help!

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@NicolasCARPi it seems like you removed access to maintainers on your fork while creating the PR and I can't rebase it.
Would you please rebase the branch against `4.2.x` to make sure things are synced?

**Comment by NicolasCARPi** [comment]
@lcobucci I don't think I unticked that checkbox, but who knows! I've updated the branch.

**Comment by lcobucci** [comment]
Thanks!

**Comment by piotr-cz** [comment]
Too bad that this has been removed from docs here: https://github.com/lcobucci/jwt/commit/fb752da3c1ae1c422bb4cf6a6d0ee86cbe9e2d86#diff-2a5cc5840033df051eb77a74837870ef13bd74dd8279f0270c498591728bce00

**Pull request merged**
