### PR TITLE
Fix argument name in `@param` annotation of `OpenSSL#doVerify()`

### PR DESCRIPTION
**Pull request by chalasr**

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM :+1:

**Comment by Ocramius** [comment]
@chalasr I see that the repo requires signed commits: could you run following and force-push please?

```sh
git rebase --exec 'git commit --amend --no-edit -n -S' -i 3.4
```

**Comment by chalasr** [comment]
@Ocramius Done!

**Comment by Ocramius** [comment]
Thanks @chalasr!

**Pull request merged**
