### PR TITLE
Silenced deprecation errors

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This will fix all the issues people have been posting recently. Firing silenced deprecation errors is the convention. See, for example, Symfony. :)

### CODE REVIEW

**Comment by lcobucci** [comment]
I already explained before, that's not the approach I want to take for this package.

Deprecation aren't errors and shouldn't be treated like errors, regardless if they come from the language or from a lib.

Thanks for your time on sending this PR, though.

**Comment by GrahamCampbell** [comment]
I am confused as to your approach here. Aren't you treating them like errors?

**Comment by lcobucci** [comment]
@GrahamCampbell I'm treating them just like the language does. Please read carefully the explanation I gave on the issue (and on click the links).

**Comment by GrahamCampbell** [comment]
Hmm, I still don't think I agree that is the best approach, from a practical perspective.

**Pull request closed without merging**
