### PR TITLE
Make it super obvious that the stable docs are at at 3.2 branch.

### PR DESCRIPTION
**Pull request by frankdejonge**
It's down under on the docs now, which is nice if you want to spend time scrolling but time is money 💰

### CODE REVIEW

**Comment by Ocramius** [comment]
Lazy :-P

**Comment by frankdejonge** [comment]
@Ocramius you are my inspiration.

**Comment by Ocramius** [comment]
@lcobucci build fails, so merge is up to you

**Comment by lcobucci** [comment]
OMG @frankdejonge managed to break the build by updating the readme, well done mate! 😂 

@Ocramius I'm working on the fix, it's safe to merge it. Thanks!

**Comment by frankdejonge** [comment]
@lcobucci I am a man of many talents.

**Pull request merged**
