### PR TITLE
Change comparison is empty.

### PR DESCRIPTION
**Pull request by AlefeVariani**
Change comparison is empty.

### CODE REVIEW

**Comment by Ocramius** [comment]
What's the reason for this change? Can you provide a test case?

**Comment by AlefeVariani** [comment]
Sorry, this change is the [empty](http://php.net/manual/en/function.empty.php) function of php, in [Parse.php](https://github.com/lcobucci/jwt/blob/master/src/Parser.php) file.
> $data == ''
> empty($data) :+1:

**Comment by Ocramius** [comment]
Yes, but why was it changed? Did you have a bug that needed this change?

**Comment by AlefeVariani** [comment]
It's not a bug, just by existing empty function that does this :)

**Comment by Ocramius** [comment]
empty is not the same of a string comparison...

**Comment by lcobucci** [comment]
@AlefeVariani first of all thanks for your contribution :smile:.

What @Ocramius is saying is that the string comparison is good enough in this case. Did you found a bug that is solved after introducing the ```empty()``` function? If so please add test cases for that, otherwise I'll closing this PR.

**Comment by AlefeVariani** [comment]
Ok, there's not bug.
Thanks @Ocramius and @lcobucci

**Pull request closed without merging**
