### PR TITLE
Avoid conflicts with other polyfills

### LINKED ISSUE #594: \JsonException does not check if it already exists before adding it
\JsonException added in https://github.com/lcobucci/jwt/commit/6728388a529847fae1e840c3bd21adb69ad889b9 should check if the class exists before declaring. We have a problem with this class because we use the symfony polyfill which also adds this class

### PR DESCRIPTION
**Pull request by digibeuk**
fixes #594

### CODE REVIEW

**Review by lcobucci — CHANGES_REQUESTED** [review]
The changeset looks good, would you please rebase this, though? This merge commit looks quite unnecessary.

**Comment by digibeuk** [comment]
> The changeset looks good, would you please rebase this, though? This merge commit looks quite unnecessary.

ah yeah, I usually rely on the squash and merge option for PRs in GH :smile: will rebase it

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@digibeuk thanks, I'll release it soon! Just waiting for a test to confirm #593

**Comment by lcobucci** [comment]
@digibeuk I didn't get a reply on that issue, so https://github.com/lcobucci/jwt/releases/tag/3.4.2 is released :+1: 

Thanks again!

**Pull request merged**
