### PR TITLE
[3.3] OutOfBoundsException: tell which header/claim failed

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by lcobucci** [comment]
@Slamdunk this is quite good but it's an improvement not a bug fix, so it should go to v3.4 :+1:

Would you please change the base branch and rebase your work?

**Comment by Slamdunk** [comment]
Mmm, dunno: it doesn't change the API, so strictly speaking about SEMVER, I don't see this as a MINOR update...
But if you ask me this again, I'll rebase immediately ^^

**Comment by Slamdunk** [comment]
By "change the API" I meant "add new API"

**Comment by lcobucci** [comment]
I get what mean, but this is not a backward compatible bugfix too. So, please rebase :+1:

**Comment by Slamdunk** [comment]
Done

**Comment by lcobucci** [comment]
@Slamdunk thanks!

**Pull request merged**
