### PR TITLE
Clarify Ecdsa\Sha512::expectedKeyLength()

### PR DESCRIPTION
**Pull request by enumag**
@lcobucci I assume the 521 is unintended typo, right? :thinking:

### CODE REVIEW

**Comment by lcobucci** [comment]
Nope, it's correct :smile:
ES512 means `ECDSA using P-521 and SHA-512`, the key size is 521 (I got confused too 😅)

**Comment by enumag** [comment]
Oh, interesting. Might be worth a comment in the code?

**Comment by Ocramius** [comment]
@enumag you can adjust your patch to include that 👍

**Comment by enumag** [comment]
Will do tomorrow. :)

**Comment by enumag** [comment]
Done.

**Review by Slamdunk — APPROVED** [review]

**Pull request merged**
