### PR TITLE
Fix deprecation notes

### PR DESCRIPTION
**Pull request by lcobucci**
As pointed out by @MasterOdin in #133 we were a bit too eager to add the deprecation notes.

This solves that, allowing users to migrate in a smooth way.

### CODE REVIEW

**Comment by lcobucci** [comment]
@MasterOdin can you please let me know if this solves the issue you raised? I don't want for this lib to annoy people with useless deprecation notes.

**Comment by MasterOdin** [comment]
Yeah, this looks like it would solve my issue in that there's a way to use non-deprecated functions for generating a token! 👍 

One thing I noticed while looking through this is that the 3.3 release uses [Builder::with](https://github.com/lcobucci/jwt/blob/3.3/src/Builder.php#L338-L347) while 4.0 uses [Builder::withClaim](https://github.com/lcobucci/jwt/blob/master/src/Builder.php#L62).

**Comment by lcobucci** [comment]
@MasterOdin well spotted! I'll fix it too. Thanks!

**Comment by lcobucci** [comment]
@MasterOdin released :+1:

**Comment by MasterOdin** [comment]
Thanks so much! :+1:

**Pull request merged**
