### PR TITLE
Add content check after key file reading

### PR DESCRIPTION
**Pull request by misantron**
Issue #207

### CODE REVIEW

**Comment by lcobucci** [comment]
@misantron sorry about the huge delay to get back to you, but can you please add tests to your changes?

**Comment by misantron** [comment]
I have no idea how to test this case. I think the only way is to mock internal php function but I don't think it's good idea. Any suggestion?

**Comment by lcobucci** [comment]
Maybe locking the file with `flock()`?

**Comment by misantron** [comment]
Ok I'll try

**Comment by lcobucci** [comment]
@misantron thanks!

**Comment by misantron** [comment]
Test is ready but the only way to prevent warnings is to use @ operator. I know it's a bad practice but it's exceptional case.

**Comment by lcobucci** [comment]
@misantron I was thinking about this... maybe using `SplFileObject` should be simpler and remove the `@`.

**Comment by misantron** [comment]
It's not a solution I think. SPL object using same PHP SAPI inside that's why behavour will be the same. And additionaly we have problems with testing because of this: https://github.com/mikey179/vfsStream/wiki/Known-Issues

**Comment by misantron** [comment]
@lcobucci if you decide to use ```SplFileObject``` I can do it in this patch.

**Pull request merged**
